### ISSUE TITLE
 No resource found ,图没传上来？

### ISSUE THREAD

**Issue by NashLegend** [shaohui10086/BottomDialog#1]
Error:(42, 54) No resource found that matches the given name (at 'src' with value '@mipmap/share_wechat_solid').
Error:(68, 54) No resource found that matches the given name (at 'src' with value '@mipmap/share_weixin_friends_solid').
Error:(94, 54) No resource found that matches the given name (at 'src' with value '@mipmap/share_weibo_solid').
Error:(120, 54) No resource found that matches the given name (at 'src' with value '@mipmap/share_qq_solid').
Error:(146, 54) No resource found that matches the given name (at 'src' with value '@mipmap/share_qqzone_solid').

**Comment by shaohui10086** [comment]
好了，已经更新上去了（￣︶￣）↗
