### ISSUE TITLE
.setCancelOutside(true)参数设置不起作用

### ISSUE THREAD

**Issue by YiBeeM** [shaohui10086/BottomDialog#10]
你好,有两个问题需要请教下:
1.我是在fragment中弹出的dialog的,.setCancelOutside(true)设置之后点击空白区域dialog不消失;
2.点击事件是在bindView中触发的?
谢谢!

**Comment by shaohui10086** [comment]
检查一下你的点击事件是不是被你的layout给吞掉了，点击事件是设置为window的，不是在bindView中设置的，看一下你的Layout的高度是多少

**Comment by van048** [comment]
@YiBeeM 
很有可能是實際使用的layout高度已經是滿屏了，所以所謂的點擊空白區域其實還是在DialogFragment裏
@shaohui10086 例子中的`dialog_layout.xml`就是這個情況，應該把`android:layout_alignParentBottom="true"`去掉
