### ISSUE TITLE
关于setCancelOutside方法

### ISSUE THREAD

**Issue by staticzh** [shaohui10086/BottomDialog#11]
在运行example的时候，showDialog方法中把布局改为dialog_edit_text后，setCancelOutside方法是生效的；当布局是dialog_layout的时候，setCancelOutside方法是不生效的，测试手机：魅蓝，华为

**Comment by shaohui10086** [comment]
好的，谢谢反馈，等我测试一下，然后给你回复

**Comment by shaohui10086** [comment]
确认是的，这是example中`dialog_layout`的布局文件写的有问题，`RelativeLayout`为`wrap_content`时，子view为`alignParentBottom`会使`wrap_content`失效，最后的效果就是`RelativeLayout`实际效果是充满全屏的，这也就是为什么`BottomDialog`的`setCancelOutside`方法不生效，因为点击事件都是在view内部的，没有被window捕获到。

解决方案就是把`RelativeLayout`换成`FrameLayout`就能生效了，代码我已经更新上去了， 你可以再试一下，如果还有什么问题，欢迎反馈\(^o^)/
