### ISSUE TITLE
控件事件监听写在bingView里不起作用吗

### ISSUE THREAD

**Issue by fansangg** [shaohui10086/BottomDialog#12]

**Comment by shaohui10086** [comment]
应该是没有问题的，你可以看下`example`下的`EditTextDialog `，我在`bindView`中设置了弹出键盘，就可以生效

**Comment by fansangg** [comment]
`@Override
    public void bindView(View v) {
        mEditsightPopupLayout = (ImageView) v.findViewById(R.id.editsight_popup_layout);
        mEditsightPopupLayout.setRotation(180.0f);
        mWindowRgb = (TextView) v.findViewById(R.id.window_rgb);
        mWindowRgb.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                LogUtils.d("onclick");

            }
        });

    }`

onclicklistener确实没有反应

**Comment by shaohui10086** [comment]
可能是你布局写的问题，你可以先写一个简单的布局，只有一个`Button`然后试着能不能收到它的点击事件

**Comment by fansangg** [comment]
谢谢，的确是我的按钮的焦点被抢了，还有一个问题，当这个dialog dismiss后，这个对象是被销毁了吗？

**Comment by shaohui10086** [comment]
不会的，`Dialog`对象还是存在的，他只是从`FragmentManager`中移除，不显示了，你可以再调用`show`再显示
