### ISSUE TITLE
dismiss相关

### ISSUE THREAD

**Issue by Yanren1225** [shaohui10086/BottomDialog#26]
怎么在bindview几调用BottomDialog的dismiss？？

**Comment by cf0566** [comment]
Fragment prev = getSupportFragmentManager().findFragmentByTag("BottomDialog");
                                if (prev != null) {
                                    BottomDialog df = (BottomDialog) prev;
                                    df.dismiss();
                                }


我也遇到这类问题了，不过我是这样解决的希望对你有帮助哈

**Comment by starock** [comment]
楼上的方法可以，刚试过了。谢谢~

**Comment by BruceZhang2017** [comment]
不行。
