### ISSUE TITLE
关于minSdkVersion的问题

### ISSUE THREAD

**Issue by FTExplore** [shaohui10086/BottomDialog#4]
@android:style/Theme.DeviceDefault.Dialog 需要api14 以上
但是gradle 里面minSdkVersion 9，应该改为14吧

**Comment by shaohui10086** [comment]
嗯，确实有点问题，刚才改了一下，没有改minSdkVersion，把api14以下的Dialog Style 改成了@android:style/Theme.Dialog"，谢谢反馈

**Comment by QuincySx** [comment]
这个问题有水平
