### ISSUE TITLE
点击外部区域无法隐藏dialog

### ISSUE THREAD

**Issue by ghost** [shaohui10086/BottomDialog#6]
dialog.setCancelOutside(true);   // 点击外部区域是否关闭，默认true
点击外部区域好像无法隐藏dialog
dialog显示的view好像是铺满整个屏幕的，所以点击其他地方没有反应。

**Comment by shaohui10086** [comment]
这是正常的，dialog内部的点击是由dialog控制的，只有dialog外部才受setCancelOutside()影响
