### ISSUE TITLE
导入报错,难道必须使用com.android.support:support-v4:24.2.1吗?

### ISSUE THREAD

**Issue by jesse920524** [shaohui10086/BottomDialog#8]
Error:Could not find com.android.support:support-v4:24.2.1.
Required by:
    ActivityTest1013:app:unspecified > com.android.support:appcompat-v7:23.4.0
    ActivityTest1013:app:unspecified > com.android.support:design:23.4.0
    ActivityTest1013:app:unspecified > com.android.support:appcompat-v7:23.4.0 > com.android.support:support-vector-drawable:23.4.0
    ActivityTest1013:app:unspecified > com.android.support:design:23.4.0 > com.android.support:recyclerview-v7:23.4.0

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>
# 

错误log如上,貌似必须安装24.2.1的v4包?可是我的开发版本是23.4.0
请问如何解决?

**Comment by shaohui10086** [comment]
你可以把 `BottomDialog` 库下的 `support-v4` exclude 掉，代码如下：

```
compile ('me.shaohui:bottomdialog:1.1.9') {
        exclude module: 'support-v4'
    }
```
