### ISSUE TITLE
怎么关闭呀？

### ISSUE THREAD

**Issue by xuguang0417** [shaohui10086/BottomDialog#9]
有没有关闭的方法？

**Comment by shaohui10086** [comment]
```
dialog.dismiss()
```

**Comment by xuguang0417** [comment]
找到了，谢啦！

**Comment by QuincySx** [comment]
在 bindView 里面 关闭 有没有快捷的方式

**Comment by WellsunZhaoZheng** [comment]
baseBottomDialog = BottomDialog.create(getSupportFragmentManager())
                .setViewListener(new BottomDialog.ViewListener() {
                    @Override
                    public void bindView(View v) {

                        // // You can do any of the necessary the operation with the view
                        etGroupName = (EditText) v.findViewById(R.id.addGroupEt);  //新建组名字
                        tvGroupSureCommit = (TextView) v.findViewById(R.id.add_group_btn); //确定新建组
                        tvGroupSureCommit.setOnClickListener(BFaceManageActivity.this);
    
                    }
                })
                .setGravity(Gravity.CENTER, 0, 100)
                .setLayoutRes(R.layout.dialog_face)
                .setDimAmount(0.1f)            // Dialog window dim amount(can change window background color）, range：0 to 1，default is : 0.2f
                .setCancelOutside(false)     // click the external area whether is closed, default is : true
                .setTag("BottomDialog")     // setting the DialogFragment tag
                .show();


onclick（view v）｛
dialog。dissmiss｝
